### ISSUE TITLE
Which algorithm you implemented in this project?

### ISSUE THREAD

**Issue by jiang-yuan** [JulienNonin/container_loading_pb#1]
Could you please give the references?
It may be helpful for me to read the code. Thank you.

**Comment by juliennonin** [comment]
Classes defined in `cargo.py` can be used to implement different algorithms. Eventually, the first algorithm that would be implemented would be the heuristic of [Araújo & Armentano 2007].

[Araújo & Armentano 2007] O. C. B. de Araújo and V. Armentano (2007), "A multi-start random constructive heuristic for the container loading problem", *Pesquisa Operacional*, vol. 27, p. 311–331, 2007.

**Comment by jiang-yuan** [comment]
> 
> 
> Classes defined in `cargo.py` can be used to implement different algorithms. Eventually, the first algorithm that would be implemented would be the heuristic of [Araújo & Armentano 2007].
> 
> [Araújo & Armentano 2007] O. C. B. de Araújo and V. Armentano (2007), "A multi-start random constructive heuristic for the container loading problem", _Pesquisa Operacional_, vol. 27, p. 311–331, 2007.

Thank you!
